### ISSUE TITLE
Segfault when running inside awesome

### ISSUE THREAD

**Issue by l0b0** [way-cooler/way-cooler#421] opened 2017-10-26 07:39 UTC
Just built and installed [way-cooler-git](https://aur.archlinux.org/packages/way-cooler-git/), but it fails catastrophically.

```
$ rustc --version
rustc 1.21.0 (3b72af97e 2017-10-09)
```

[pkgbuild.log](https://github.com/way-cooler/way-cooler/files/1417360/pkgbuild.log)
[segfault.log](https://github.com/way-cooler/way-cooler/files/1417361/segfault.log)

**Comment by Timidger** [comment] 2017-10-26 13:53
Can you get a core dump / back trace from the segfault?

**Comment by l0b0** [comment] 2017-10-27 07:29
```
$ coredumpctl dump --output=way-cooler.core /usr/bin/way-cooler 26053
           PID: 26053 (way-cooler)
           UID: 1000 (victor)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Fri 2017-10-27 20:19:49 NZDT (6min ago)
  Command Line: way-cooler
    Executable: /usr/bin/way-cooler
 Control Group: /user.slice/user-1000.slice/session-c5.scope
          Unit: session-c5.scope
         Slice: user-1000.slice
       Session: c5
     Owner UID: 1000 (victor)
       Boot ID: f0128ca74eff441e9fa52ee5f3e1b72b
    Machine ID: 9d30538abea1471ca2f5225e78cc05c2
      Hostname: l0b0k
       Storage: /var/lib/systemd/coredump/core.way-cooler.1000.f0128ca74eff441e9fa52ee5f3e1b72b.26053.1509088789000000.lz4
       Message: Process 26053 (way-cooler) of user 1000 dumped core.
                
                Stack trace of thread 26053:
                #0  0x00007f8516da4137 wl_list_remove (libwayland-server.so.0)
                #1  0x00007f8518c3ce99 n/a (libwlc.so.0)
                #2  0x00007f8518c1ea47 n/a (libwlc.so.0)
                #3  0x00007f8518c3a52c n/a (libwlc.so.0)
                #4  0x00007f8518c3ade6 n/a (libwlc.so.0)
                #5  0x00007f8516d9fb82 n/a (libwayland-server.so.0)
                #6  0x00007f8516d9fce1 wl_client_destroy (libwayland-server.so.0)
                #7  0x00007f8516d9fdb9 n/a (libwayland-server.so.0)
                #8  0x00007f8516da19b2 wl_event_loop_dispatch (libwayland-server.so.0)
                #9  0x00007f8516da014c wl_display_run (libwayland-server.so.0)
                #10 0x00007f8518c37f4d wlc_run (libwlc.so.0)
                #11 0x000055769432af63 n/a (way-cooler)
                #12 0x000055769443441d n/a (way-cooler)
                #13 0x000055769442db8c n/a (way-cooler)
                #14 0x00007f8517317f6a __libc_start_main (libc.so.6)
                #15 0x000055769426a83a n/a (way-cooler)
                
                Stack trace of thread 26055:
                #0  0x00007f85178d238d pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x000055769441e38f n/a (way-cooler)
                #2  0x0000557694425250 n/a (way-cooler)
                #3  0x000055769426fe52 n/a (way-cooler)
                #4  0x00005576942759c8 n/a (way-cooler)
                #5  0x000055769443441d n/a (way-cooler)
                #6  0x00005576942ab64a n/a (way-cooler)
                #7  0x000055769442c50c n/a (way-cooler)
                #8  0x00007f85178cc08a start_thread (libpthread.so.0)
                #9  0x00007f85173ed24f __clone (libc.so.6)
                
                Stack trace of thread 26056:
                #0  0x00007f85173e2d4b __poll (libc.so.6)
                #1  0x00007f85187ae2b1 n/a (libdbus-1.so.3)
                #2  0x00007f85187acf1d n/a (libdbus-1.so.3)
                #3  0x00007f851879563e n/a (libdbus-1.so.3)
                #4  0x00007f8518797c22 n/a (libdbus-1.so.3)
                #5  0x000055769436b016 n/a (way-cooler)
                #6  0x0000557694270f33 n/a (way-cooler)
                #7  0x0000557694275a30 n/a (way-cooler)
                #8  0x000055769443441d n/a (way-cooler)
                #9  0x00005576942ab4b0 n/a (way-cooler)
                #10 0x000055769442c50c n/a (way-cooler)
                #11 0x00007f85178cc08a start_thread (libpthread.so.0)
                #12 0x00007f85173ed24f __clone (libc.so.6)
```
[way-cooler.core.gz](https://github.com/way-cooler/way-cooler/files/1421127/way-cooler.core.gz)

**Comment by Timidger** [comment] 2017-10-28 21:51
Sorry for the late reply.

There aren't debug symbols in that core dump, can you try compiling with debug symbols enabled? Not sure why they aren't there since I thought I enabled them for release builds...

But I also can't reproduce your issue (I also run Arch). Can you reproduce this issue at all with Sway? It's failing in basic wlc initialization, so maybe it's an issue with that?

**Comment by Timidger** [comment] 2017-10-28 21:53
Also your title indicates it segfaults in Awesome, does it also fail when running standalone (e.g in a TTY)?

**Comment by WarpspeedSCP** [comment] 2017-11-03 02:50
This also happens in i3. Also, when I tried starting the AUR version via tty, it practically froze my machine. Luckily, I could restart gracefully with ctrl-alt-del.

**Comment by Timidger** [comment] 2017-12-02 19:10
@WarpspeedSCP  Do you have logs from this? Sorry for the late reply, this issue has slipped a bit since it's something I can't reproduce well.

One thing that leaps out at me is that the output size changes from a higher resolution to a lower one. That might be causing the issue, I'm not sure. I'm not sure why it defaults to that lower resolution or not. 

Can you reproduce this issue with Sway? If not, they might be doing something different that I need to handle. If you can reproduce, this is more than likely a wlc issue that will be fixed with the move to wlroots.

**Comment by Timidger** [comment] 2017-12-11 23:15
If someone has a stacktrace of this issue please bump this issue. Since I can't reproduce it and I haven't received a stacktrace I cannot debug this. So I will close for now as WONTFIX

**Closed by Timidger** 2017-12-11 23:15 UTC
Labels: Bug, Unsound
