### ISSUE TITLE
Launching way-cooler from X works, but not from tty

### ISSUE THREAD

**Issue by Sh4d1** [way-cooler/way-cooler#351] opened 2017-08-03 18:22 UTC
Hey ! 

I installed way-cooler on VoidLinux, and it is working when I launch it from X11, but when I try to launch it from the TTY, it does not work. 
I have all the INFO about the environment variables but I have a return code of 1 with no explanation.. Any idea ? 

Thank you :)

**Comment by Timidger** [comment] 2017-08-05 00:39
Couple things to help debug:
1) Get the log output (e.g `way-cooler &> log.txt`)
2) Run it through gdb, ensure it's not silently segfaulting. If it is, a core dump would be great (though a stack trace might be sufficient).
3) Does [sway](https://github.com/SirCmpwn/sway) work fine in the tty? If not, do you have a nvidia card / dual card setup? If so, then there's more work necessary. Namely, you need the newest version of wlc, or need to ensure you're using nouveau, and finally if you are using a multi card setup please set the `WLC_DRM_DEVICE` to the appropriate card (e.g `CARD1`)

**Comment by Sh4d1** [comment] 2017-08-05 08:24
So here is my log : 
```
Launching way-cooler...
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:158 Logger initialized, setting wlc handlers.
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 HOME: /home/patrik
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 USER: patrik
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 SHELL: /bin/zsh
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 TERM: linux
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 PATH: /home/patrik/work/wtftw/target/debug:/home/patrik/.cargo/bin:/home/patrik/bin:/home/patrik/.gem/ruby/2.3.0/bin:/home/patrik/ensimag/gl/Projet_GL/src/test/script/launchers:/home/patrik/ensimag/gl/Projet_GL/src/test/script:/home/patrik/ensimag/gl/GL/global/bin:/home/patrik/.pyenv/bin:/home/patrik/.Pokemon-Terminal:/home/patrik/ensimag/gl/Projet_GL/src/main/bin:/home/patrik/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin:/opt/void-packages
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 MAIL: /var/spool/mail/patrik
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LOGNAME: patrik
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 XDG_SESSION_COOKIE: pineapple-1501926266.404119-1897922625
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 XDG_RUNTIME_DIR: /run/user/1000
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 SHLVL: 1
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 PWD: /home/patrik
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 OLDPWD: /home/patrik
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LS_COLORS: no=00:fi=00:di=01;34:ln=00;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=41;33;01:ex=00;32:ow=0;41:*.cmd=00;32:*.exe=01;32:*.com=01;32:*.bat=01;32:*.btm=01;32:*.dll=01;32:*.tar=00;31:*.tbz=00;31:*.tgz=00;31:*.rpm=00;31:*.deb=00;31:*.arj=00;31:*.taz=00;31:*.lzh=00;31:*.lzma=00;31:*.zip=00;31:*.zoo=00;31:*.z=00;31:*.Z=00;31:*.gz=00;31:*.bz2=00;31:*.tb2=00;31:*.tz2=00;31:*.tbz2=00;31:*.avi=01;35:*.bmp=01;35:*.fli=01;35:*.gif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mng=01;35:*.mov=01;35:*.mpg=01;35:*.pcx=01;35:*.pbm=01;35:*.pgm=01;35:*.png=01;35:*.ppm=01;35:*.tga=01;35:*.tif=01;35:*.xbm=01;35:*.xpm=01;35:*.dl=01;35:*.gl=01;35:*.wmv=01;35:*.aiff=00;32:*.au=00;32:*.mid=00;32:*.mp3=00;32:*.ogg=00;32:*.voc=00;32:*.wav=00;32:*.patch=00;34:*.o=00;32:*.so=01;35:*.ko=01;31:*.la=00;33
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LANG: en_US.UTF-8
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LC_COLLATE: en_US.UTF-8
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 MOZ_PLUGIN_PATH: /usr/lib/mozilla/plugins
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 ZSH: /home/patrik/.oh-my-zsh
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 EDITOR: vim
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 VISUAL: vim
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LC_CTYPE: en_US.UTF-8
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LC_MESSAGES: en_US.UTF-8
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LC_MONETARY: en_US.UTF-8
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LC_NUMERIC: en_US.UTF-8
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LC_TIME: en_US.UTF-8
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LC_ALL: en_US.UTF-8
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LANGUAGE: en_US.UTF-8
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LESSCHARSET: utf-8
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 _JAVA_AWT_WM_NONREPARENTING: 1
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 SSH_KEY_PATH: ~/.ssh/id_rsa
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LESS_TERMCAP_mb:
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LESS_TERMCAP_md:
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LESS_TERMCAP_me:
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LESS_TERMCAP_se:
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LESS_TERMCAP_so:
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LESS_TERMCAP_ue:
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LESS_TERMCAP_us:
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 PAGER: less
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LESS: -R
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 LSCOLORS: Gxfxcxdxbxegedabagacab
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 DIRHISTORY_SIZE: 30
 INFO [way_cooler] /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:163 _: /home/patrik/.cargo/bin/way-cooler

```
I'm runninw wlc 0.0.10, which is the latest version I think. 
Sway is running, but it is slow, the mouse is not really reactive. 
I have a Intel chipset for graphics and I'm not running multi card setup. 

With gdb I'm not seeing any segfault. 
Here is what I get : 
```
Breakpoint 2, rustwlc::init () at /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/rustwlc-0.6.2/src/lib.rs:203
203         if unsafe { wlc_init() } {
(gdb) bt
#0  rustwlc::init () at /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/rustwlc-0.6.2/src/lib.rs:203
#1  0x00005555556069de in way_cooler::main () at /home/patrik/.cargo/registry/src/github.com-1ecc6299db9ec823/way-cooler-0.6.1/src/main.rs:204
(gdb) s
[Inferior 1 (process 4087) exited with code 01]
(gdb) quit
```

**Comment by Timidger** [comment] 2017-08-05 19:26
Ok, after ensuring it wasn't wlc v0.0.10 causing the issue (i'm still running 0.0.9 on my machine, but it shouldn't (and doesn't) make a difference). By my very, very rough guess the reason this is failing for you is because you don't use systemd. As a quick sanity test, does `way-cooler` have setuid privileges? If so, then the problem is probably somewhere in the init code. If you want to debug this further, I suggest looking at the setup code that sway does (e.g [all the lines in this method before this point](https://github.com/SirCmpwn/sway/blob/master/sway/main.c#L376) and see what's different from [our init code](https://github.com/way-cooler/way-cooler/blob/master/src/main.rs#L204)

**Comment by Sh4d1** [comment] 2017-08-05 19:39
Yep it has 755 ! Do you know what I should search for ? I'm gonna take a look when I have some time :) 
Thank you :)

**Comment by Timidger** [comment] 2017-08-05 19:47
@Sh4d1 It probably [these lines](https://github.com/SirCmpwn/sway/blob/master/sway/main.c#L296) that you'd have to add to Way Cooler though I'm not 100% sure. You might also want to see the [issues about systemd posted for sway](https://github.com/SirCmpwn/sway/search?q=systemd&type=Issues) to get a better idea about how they might have ran into issues like this.

**Comment by Sh4d1** [comment] 2017-08-05 20:18
Hmm, the verbose option ? 
I checked the issues, the only one I found is [this one](https://github.com/SirCmpwn/sway/issues/1022) which could be relevant, I tried to change the cap, and `chmod +s` but it does not solve the issue..

**Comment by Timidger** [comment] 2017-08-05 21:15
@Sh4d1 
> Hmm, the verbose option ?

Woops, wrong line sorry. Was going off an old version I have downloaded. Meant [this line](https://github.com/SirCmpwn/sway/blob/master/sway/main.c#L354).

If you do `chmod +s`, make sure you are doing that as root and that you don't lose the other flags set on it. I remember early on developing Way Cooler in an a non-systemd environment and that was an annoying gotcha.

**Comment by Guppster** [comment] 2017-09-12 04:23
@Sh4d1 

Did you manage to get this working? Iv run into the exact same problem

**Comment by Sh4d1** [comment] 2017-09-12 07:47
@Guppster No, still have the same problem with 0.6.2 ..

**Comment by Timidger** [comment] 2017-09-12 14:55
Ensure your binary has setuid privileges, and that it isn't in your home. On many systems setuid doesn't work in /home/ for security reasons. If so, try installing it manually to e.g `/usr/bin`

**Comment by Guppster** [comment] 2017-09-13 21:01
@Timidger 
Thanks! I had followed the manual install steps and cargo installed it to `~/.cargo/bin` 
so i moved it to `/usr/bin` and also ran `chown root way-cooler` which seems to have fixed that problem. But now im getting a segmentation fault and the strace ends with a permission denied statement

Log: https://gist.github.com/Guppster/595b92d8d49c0d390c42dfa630889fb5
strace: https://gist.github.com/Guppster/9cf1fbc5f0a434eace5aea6403e123d4

**Comment by Timidger** [comment] 2017-09-13 21:54
@Guppster 

Have you tried the fix in [this previously linked sway issue that might be of interest](https://github.com/SirCmpwn/sway/issues/1022)? It recommends to run the snippet adapted from [here](https://github.com/SirCmpwn/sway/wiki/Sway-without-systemd-on-Arch-Linux)

```bash
setcap cap_sys_tty_config=ep /usr/bin/way-cooler
```

**Comment by Guppster** [comment] 2017-09-13 22:07
Yeah i have already tried that and it didnt do anything. The latest version of sway actually produces an error message telling you to either set suid or setcap, not both. 

I'm going to try reinstalling using the install script and different combinations of setcap / suid / install location .... i really want a wayland tiling wm lol

**Comment by Timidger** [comment] 2017-09-13 22:10
I haven't used VoidLinux before, but I have used Way Cooler without systemd before. If I remember correctly, the correct incantation to put it in /usr/bin was:

```bash
cp ~/.cargo/bin/way-cooler /usr/bin   # or where ever the binary is
chown root /usr/bin/way-cooler
chmod u+s /usr/bin/way-cooler
```

I noticed if I `chown root` _after_ `chmod u+s` then it loses the setuid bit.

As a final sanity test, you might try and see if it works as root (e.g 'sudo way-cooler`).

I'll take a more in-depth look at this after work.

**Comment by Sh4d1** [comment] 2017-09-13 22:15
@Guppster @Timidger just changing the location worked for me ! 
Here is the ls of the binary : ```-rwsr-xr-x 1 root root 26590208 Sep 12 18:21 /usr/bin/way-cooler```

**Comment by Timidger** [comment] 2017-09-13 22:21
Cool, glad to hear you guys sorted it out. I'm going to go ahead and close this issue. I have created #398 in order to fix this issue in the long term. Feel free to send a PR if you guys want this to be fixed sooner rather than later ;)

**Closed by Timidger** 2017-09-13 22:21 UTC
Labels: Distribution, Question

**Comment by Guppster** [comment] 2017-09-13 22:33
I'm still getting a segfault but I think the results from @Sh4d1 prove its unrelated to this issue. If i figure it out i'll document it somewhere and edit this post. Thanks for the quick replies @Timidger :)

**Comment by Timidger** [comment] 2017-09-13 22:45
@Guppster feel free to make another issue specifically about the segfault, copying the info you gave here and I can help you resolve it later.

**Comment by Sh4d1** [comment] 2017-09-14 09:28
@Guppster Maybe you could take a look here, it could be worth a shot : https://github.com/mk-fg/pulseaudio-mixer-cli/issues/17
